	
	CREATE TABLE LearnerBio (
		LearnerId INT IDENTITY(1, 1) PRIMARY KEY,
		FirstName VARCHAR(55) NOT NULL,
		MiddleName VARCHAR(55) NULL,
		LastName VARCHAR(55) NOT NULL,
		Gender VARCHAR(10) NOT NULL
			CHECK(Gender IN ('Male', 'Female')),
		DateofBirth DATE NOT NULL,
		IDNumber VARCHAR(20) NULL,
		Email VARCHAR(255) NOT NULL UNIQUE,
		Cell VARCHAR(20) NOT NULL UNIQUE,
		Country VARCHAR(55) NOT NULL,
		Province VARCHAR(55) NOT NULL,
		City VARCHAR(55) NOT NULL,
		SchoolName VARCHAR(255) NOT NULL,
		Grade VARCHAR(10) NOT NULL,
		Stream VARCHAR(55) NOT NULL,
		CreatedAt DATETIME DEFAULT GETDATE()
	)
